# Hello, _nbpresent_!

In [51]:
import nbpresent
nbpresent.__version__

'3.0.2'

## Exploratory data analysis

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pylab as plt
%matplotlib inline

In [2]:
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)

In [3]:
user_info_train = pd.read_csv('./Credit/train/user_info_train.txt',names=['ID','gender','career','education','marriage','hukou'],header=None)
loan_time_train = pd.read_csv('./Credit/train/loan_time_train.txt',names=['ID','timestamp_money'],header=None)
overdue_train = pd.read_csv('./Credit/train/overdue_train.txt',names=['ID','Label'],header=None)
bank_detail_train = pd.read_csv('./Credit/train/bank_detail_train.txt',names=['ID','timestamp_bank','type','money','salary'],header=None)
browse_history_train = pd.read_csv('./Credit/train/browse_history_train.txt',names=['ID','timestamp_browse','browse_data','browser_code'],header=None)
bill_detail_train = pd.read_csv('./Credit/train/bill_detail_train.txt',names=['ID','timestamp_bill','bank_id','last_bill','last_repayment','credit_line','current_balance','minimum_payments','amount_transactions','current_money','adjust_money','cycle_interest','available_money','cash_advance','repayment_status'],header=None)

In [4]:
data_user_train = pd.merge(user_info_train,pd.merge(loan_time_train,overdue_train,on='ID',how='inner'),on='ID',how='inner')
data_user_train = data_user_train.apply(lambda x:x.astype(str))

In [5]:
data_user_train.duplicated().sum()

0

In [6]:
data_user_train.isnull().sum()

ID                 0
gender             0
career             0
education          0
marriage           0
hukou              0
timestamp_money    0
Label              0
dtype: int64

In [7]:
pd.crosstab(data_user_train.gender,data_user_train.Label,margins=True)

Label       0     1    All
gender
0        1015   654   1669
1       38616  5638  44254
2        8782   891   9673
All     48413  7183  55596

In [8]:
pd.crosstab(data_user_train.career,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label          0         1
career
0       0.796196  0.203804
1       0.817204  0.182796
2       0.873536  0.126464
3       0.873516  0.126484
4       0.858909  0.141091

In [9]:
pd.crosstab(data_user_train.gender,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label          0         1
gender
0       0.608149  0.391851
1       0.872599  0.127401
2       0.907888  0.092112

In [10]:
pd.crosstab(data_user_train.education,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label             0         1
education
0          0.796748  0.203252
1          0.920354  0.079646
2          0.904161  0.095839
3          0.873481  0.126519
4          0.856447  0.143553

In [11]:
pd.crosstab(data_user_train.marriage,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label            0         1
marriage
0         0.797297  0.202703
1         0.873735  0.126265
2         0.866678  0.133322
3         0.871021  0.128979
4         0.857240  0.142760
5         0.769231  0.230769

In [12]:
pd.crosstab(data_user_train.hukou,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label         0         1
hukou
0      0.796748  0.203252
1      0.881146  0.118854
2      0.862120  0.137880
3      0.880964  0.119036
4      0.863963  0.136037

## Bank information extraction

### 净收入

In [13]:
bank_detail_train['money_direction'] = bank_detail_train['type'].replace({0:1,1:-1})*bank_detail_train['money']
data_net = bank_detail_train.groupby(['ID'])['money_direction'].agg({'sum','count','mean'}).rename(columns=dict(sum='sum_total',count='freq_total',mean='mean_total'))
data_net['ID'] = data_net.index
data_net.reset_index(drop = True)
data_net['ID'] = data_net['ID'].apply(lambda x:str(x))

###  收入信息汇总

In [14]:
data_income = bank_detail_train[bank_detail_train.type==0].groupby(['ID'])['money'].agg({'sum','count','mean'}).rename(columns=dict(sum='sum_income', count='freq_income',mean='mean_income'))
data_income['ID'] = data_income.index
data_income.reset_index(drop = True)
data_income['ID'] = data_income['ID'].apply(lambda x:str(x))

### 支出信息汇总

In [15]:
data_spend = bank_detail_train[bank_detail_train.type==1].groupby(['ID'])['money'].agg({'sum','count','mean'}).rename(columns=dict(sum='sum_spend', count='freq_spend',mean='mean_spend'))
data_spend['ID'] = data_spend.index
data_spend.reset_index(drop = True)
data_spend['ID'] = data_spend['ID'].apply(lambda x:str(x))

In [16]:
data_bank = pd.merge(pd.merge(pd.merge(data_user_train,data_net,on='ID',how='left'),data_income,on='ID',how='left'),data_spend,on='ID',how='left')

In [17]:
data_bank.head()

     ID gender career education marriage hukou timestamp_money Label    sum_total  mean_total  freq_total   sum_income  mean_income  freq_income    sum_spend  mean_spend  freq_spend
0  3150      1      2         4        1     4      5919867087     0          NaN         NaN         NaN          NaN          NaN          NaN          NaN         NaN         NaN
1  6965      1      2         4        3     2      5923841487     0 -2261.681747   -6.213411       364.0   972.850228    12.971336         75.0  3234.531975   11.192152       289.0
2  1265      1      3         4        3     1      5915892687     0 -1954.250868   -4.664083       419.0  1708.206195    13.665650        125.0  3662.457063   12.457337       294.0
3  6360      1      2         4        3     2      5923495887     0          NaN         NaN         NaN          NaN          NaN          NaN          NaN         NaN         NaN
4  2583      2      2         2        1     1      5917275087     0 -4327.835360   -5.207985       831.0  2736.475318    12.847302        213.0  7064.310678   11.430923       618.0

## Browser information extraction

In [18]:
data_browse = browse_history_train.loc[:, ['ID', 'browse_data']].groupby(['ID']).mean()

In [19]:
data_browse

       browse_data
ID
2       116.091954
3       112.824561
4       106.494505
6       110.000000
7       111.527778
8       106.128713
10      113.718750
12      109.325581
14       98.500000
15      111.318182
16      115.705882
17      113.338983
18      111.900000
19      101.911111
20      117.424242
21      117.017241
22      116.900000
23      113.379310
24      108.142857
25      101.522727
28      118.208333
29      118.880000
30      101.333333
31      117.633663
32      117.500000
33      115.538462
34      122.542857
35      118.136364
36      114.210526
37      102.794872
...            ...
55564   113.239669
55565    89.255814
55566   113.833333
55567   116.069767
55569   112.910448
55570   106.818182
55571   120.402985
55572   111.065217
55573   108.956522
55574   113.266667
55576   108.614286
55577   108.553571
55578   111.900000
55579   117.550725
55580   120.474576
55581   119.127273
55582   105.937500
55583    97.894737
55584   112.509615
55585   117.340426
55586   115.000000
55587   120.117647
55588   120.380282
55589   115.934066
55590   110.833333
55592   118.409091
55593   109.497207
55594   108.375000
55595   112.253968
55596   110.833333

[47330 rows x 1 columns]

## Bill information extraction

In [20]:
bill_detail_train.columns

Index(['ID', 'timestamp_bill', 'bank_id', 'last_bill', 'last_repayment', 'credit_line', 'current_balance', 'minimum_payments', 'amount_transactions', 'current_money', 'adjust_money', 'cycle_interest', 'available_money', 'cash_advance', 'repayment_status'], dtype='object')

In [21]:
bank_detail_train.columns

Index(['ID', 'timestamp_bank', 'type', 'money', 'salary', 'money_direction'], dtype='object')

In [22]:
bill_detail_train.head()

     ID  timestamp_bill  bank_id  last_bill  last_repayment  credit_line  current_balance  minimum_payments  amount_transactions  current_money  adjust_money  cycle_interest  available_money  cash_advance  repayment_status
0  3150      5906744363        6  18.626118       18.661937    20.664418        18.905766         17.847133                    1            0.0           0.0             0.0              0.0     19.971271                 0
1  3150      5906744401        6  18.905766       18.909954    20.664418        19.113305         17.911506                    1            0.0           0.0             0.0              0.0     19.971271                 0
2  3150      5906744427        6  19.113305       19.150290    20.664418        19.300194         17.977610                    1            0.0           0.0             0.0              0.0     19.971271                 0
3  3150      5906744515        6  19.300194       19.300280    21.000890        20.303240         18.477177                    1            0.0           0.0             0.0              0.0     20.307743                 0
4  3150      5906744562        6  20.303240       20.307744    21.000890        20.357134         18.510985                    1            0.0           0.0             0.0              0.0     20.307743                 0

In [27]:
data_bill = bill_detail_train.groupby(['ID'])['credit_line','cash_advance','amount_transactions'].sum()

In [26]:
bill_detail_train.groupby(['ID'])['credit_line','cash_advance','amount_transactions'].sum()

        credit_line  cash_advance  amount_transactions
ID
2        428.696405    163.013888                   58
3         36.723666      0.000000                    4
4        577.987348    281.104005                    2
5         41.328836     39.942542                    0
6        863.847364    579.114225                  122
7       2202.883453   1224.652884                  254
8         84.279532     81.506944                    0
9        408.343390    234.710278                    6
10      3934.936295   1214.521749                  117
11       237.178082    228.860313                   77
12       737.151368    709.497762                  117
13      1240.840880    596.561064                   24
14       235.905347     39.229192                    6
15       133.790325    128.532831                    0
16       674.653930    653.166373                    6
17      2711.410006   1748.134966                  182
18      2007.005844   2007.005844                    0
19       933.137549    901.945934                   85
20       256.095944      0.000000                   33
21       307.403807      0.000000                   19
22        58.381335      0.000000                    2
23         0.000000      0.000000                    8
24     20203.960983  15565.258645                 3162
25       155.683560    131.371086                    0
26       718.965756    347.006214                    0
27       619.932540    399.425410                   77
28       143.228680      0.000000                    8
29       266.769720    257.065662                    0
30       437.888529    218.880787                   19
32       136.223115    131.371086                   11
...             ...           ...                  ...
55564    138.302556     19.460445                    8
55565    560.841039    309.696701                    5
55566   1437.517585    991.004089                  112
55567      0.000000      0.000000                    3
55568     44.738332     43.352038                    0
55569    470.502864    453.867336                   44
55570     82.657672     59.913813                   15
55571    142.571485    140.492044                    0
55572    139.352609    133.332744                   16
55573     83.962322     82.576026                   12
55574   1376.633553    724.874885                   43
55575     20.153592     19.460445                    0
55576     39.942542      0.000000                    0
55577     20.664418     19.971271                    0
55578    241.981552     39.942542                    0
55579    402.891155    289.171845                    0
55580    105.992723     84.780184                    1
55581     59.244381     55.085499                    4
55582     65.289090     63.209649                    0
55584    258.187170    175.185472                    3
55585     66.955035     64.875592                    0
55588   1338.075157      0.000000                  111
55589    237.684222    116.762670                    0
55590    142.356725    138.197843                    4
55591    586.019356    353.062728                   13
55592    100.244712     98.858418                    0
55593    801.861528    429.780754                    0
55594    488.454670    214.753480                   17
55595    529.909934    519.512729                   16
55596    174.104240    168.559064                    0

[53174 rows x 3 columns]

In [28]:
bill_detail_train.columns

Index(['ID', 'timestamp_bill', 'bank_id', 'last_bill', 'last_repayment', 'credit_line', 'current_balance', 'minimum_payments', 'amount_transactions', 'current_money', 'adjust_money', 'cycle_interest', 'available_money', 'cash_advance', 'repayment_status'], dtype='object')

In [41]:
bill_detail_train['bill_credit'] = bill_detail_train.last_bill/bill_detail_train.credit_line

In [47]:
sum((bill_detail_train.last_bill-bill_detail_train.credit_line) > 0)/len(bill_detail_train)*100

24.016923012439921