In [1]:
import pandas as pd
import os
import matplotlib.pylab as plt
%matplotlib inline

In [2]:
user_info_train = pd.read_csv('./Credit/train/user_info_train.txt',names=['ID','gender','career','education','marriage','hukou'],header=None)
loan_time_train = pd.read_csv('./Credit/train/loan_time_train.txt',names=['ID','timestamp_money'],header=None)
overdue_train = pd.read_csv('./Credit/train/overdue_train.txt',names=['ID','Label'],header=None)

user_info_test = pd.read_csv('./Credit/test/user_info_test.txt',names=['ID','gender','career','education','marriage','hukou'],header=None)
loan_time_test = pd.read_csv('./Credit/test/loan_time_test.txt',names=['ID','timestamp_money'],header=None)
usersID_test= pd.read_csv('./Credit/test/usersID_test.txt',names=['ID','Label'],header=None)

In [3]:
# bank_detail_test = pd.read_csv('./Credit/test/bank_detail_test.txt',names=['ID','timestamp_bank','type','money','salary'],header=None)
# browse_history_test = pd.read_csv('./Credit/test/browse_history_test.txt',names=['ID','timestamp_browse','browse_data','browser_code'],header=None)
# bill_detail_test = pd.read_csv('./Credit/test/bill_detail_test.txt',names=['ID','timestamp_bill','bank_id','last_bill','last_repayment','credit_line','current_balance','minimum_payments','amount_transactions','current_money','adjust_money','cycle_interest','available_money','cash_advance','repayment_status'],header=None)
# bank_detail_train = pd.read_csv('./Credit/train/bank_detail_train.txt',names=['ID','timestamp_bank','type','money','salary'],header=None)
# browse_history_train = pd.read_csv('./Credit/train/browse_history_train.txt',names=['ID','timestamp_browse','browse_data','browser_code'],header=None)
# bill_detail_train = pd.read_csv('./Credit/train/bill_detail_train.txt',names=['ID','timestamp_bill','bank_id','last_bill','last_repayment','credit_line','current_balance','minimum_payments','amount_transactions','current_money','adjust_money','cycle_interest','available_money','cash_advance','repayment_status'],header=None)

In [4]:
data_user_train = pd.merge(user_info_train,pd.merge(loan_time_train,overdue_train,on='ID',how='inner'),on='ID',how='inner')

In [5]:
data_user_test = pd.merge(user_info_test,pd.merge(loan_time_test,usersID_test,on='ID',how='inner'),on='ID',how='inner')

In [6]:
data_user_train = data_user_train.apply(lambda x:x.astype(str))
data_user_test = data_user_test.apply(lambda x:x.astype(str))

In [7]:
data_user_train.describe()

           ID gender career education marriage  hukou timestamp_money  Label
count   55596  55596  55596     55596    55596  55596           55596  55596
unique  55596      3      5         5        6      5             191      2
top     54077      1      2         3        1      1      5927556687      0
freq        1  44254  41150     23530    25098  17105            1256  48413

In [8]:
data_user_test.describe()

           ID gender career education marriage  hukou timestamp_money  Label
count   13899  13899  13899     13899    13899  13899           13899  13899
unique  13899      3      5         5        6      5              23      1
top     55880      1      2         4        1      1      5933604687    nan
freq        1  10829  10284      5930     7068   4330             907  13899

In [113]:
data_user_train.duplicated().sum()

0

In [111]:
data_user_train.isnull().sum()

ID                 0
gender             0
career             0
education          0
marriage           0
hukou              0
timestamp_money    0
Label              0
dtype: int64

In [70]:
rep(data_user_train)

Replicate Data: 0
 ID                 0
gender             0
career             0
education          0
marriage           0
hukou              0
timestamp_money    0
Label              0
dtype: int64

In [60]:
pd.crosstab(data_user_train.gender,data_user_train.Label,margins=True)

Label       0     1    All
gender
0        1015   654   1669
1       38616  5638  44254
2        8782   891   9673
All     48413  7183  55596

In [96]:
pd.crosstab(data_user_train.career,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label          0         1
career
0       0.796196  0.203804
1       0.817204  0.182796
2       0.873536  0.126464
3       0.873516  0.126484
4       0.858909  0.141091

In [97]:
pd.crosstab(data_user_train.gender,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label          0         1
gender
0       0.608149  0.391851
1       0.872599  0.127401
2       0.907888  0.092112

In [106]:
data_user_train.columns

Index(['ID', 'gender', 'career', 'education', 'marriage', 'hukou',
       'timestamp_money', 'Label'],
      dtype='object')

In [107]:
pd.crosstab(data_user_train.education,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label             0         1
education
0          0.796748  0.203252
1          0.920354  0.079646
2          0.904161  0.095839
3          0.873481  0.126519
4          0.856447  0.143553

In [108]:
pd.crosstab(data_user_train.marriage,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label            0         1
marriage
0         0.797297  0.202703
1         0.873735  0.126265
2         0.866678  0.133322
3         0.871021  0.128979
4         0.857240  0.142760
5         0.769231  0.230769

In [109]:
pd.crosstab(data_user_train.hukou,data_user_train.Label).apply(lambda x: x/x.sum(), axis=1)

Label         0         1
hukou
0      0.796748  0.203252
1      0.881146  0.118854
2      0.862120  0.137880
3      0.880964  0.119036
4      0.863963  0.136037

In [161]:
bank_detail_train = pd.read_csv('./Credit/train/bank_detail_train.txt',names=['ID','timestamp_bank','type','money','salary'],header=None)
browse_history_train = pd.read_csv('./Credit/train/browse_history_train.txt',names=['ID','timestamp_browse','browse_data','browser_code'],header=None)
bill_detail_train = pd.read_csv('./Credit/train/bill_detail_train.txt',names=['ID','timestamp_bill','bank_id','last_bill','last_repayment','credit_line','current_balance','minimum_payments','amount_transactions','current_money','adjust_money','cycle_interest','available_money','cash_advance','repayment_status'],header=None)

In [163]:
browse_history_train.groupby('ID')['ID'].count()

ID
2        1305
3         342
4         364
6          15
7        1008
8        1111
10        320
12        516
14        208
15        154
16        153
17       2478
18        100
19       2025
20        594
21        348
22        160
23        348
24        189
25        308
28       1440
29        275
30        378
31        606
32         96
33        182
34        350
35        154
36       1140
37        312
         ...
55564    1210
55565     301
55566     180
55567     602
55569     871
55570     154
55571     402
55572     414
55573     230
55574     270
55576     630
55577     448
55578      80
55579     759
55580     531
55581     990
55582     432
55583     152
55584     728
55585     141
55586     770
55587     136
55588     568
55589     364
55590     168
55592     396
55593     179
55594     960
55595     630
55596     120
Name: ID, dtype: int64

In [164]:
bank_detail_train.columns

Index(['ID', 'timestamp_bank', 'type', 'money', 'salary'], dtype='object')

In [172]:
bank_detail_train.columns

Index(['ID', 'timestamp_bank', 'type', 'money', 'salary'], dtype='object')

In [173]:
bank_detail_train.head()

     ID  timestamp_bank  type      money  salary
0  6965      5894316387     0  13.756664       0
1  6965      5894321388     1  13.756664       0
2  6965      5897553564     0  14.449810       0
3  6965      5897563463     1  10.527763       0
4  6965      5897564598     1  13.651303       0

In [226]:
bank_detail_train['money2'] = bank_detail_train['type'].replace({0:1,1:-1})*bank_detail_train['money']
bank_detail_train.groupby(['ID'])['money2'].sum()

ID
1         -195.332507
3        -2707.084161
4         -965.083338
9           45.288586
10        -456.650397
14       -1103.818050
16        -456.937171
21       -3113.071570
22         -95.838270
23       -2022.347780
25       -1560.388233
26        -426.445213
29       -4902.676475
31      -11080.751312
32       -1622.899614
33       -3399.264795
35        -272.343989
36       -6292.623945
37       -3288.245032
38       -1522.884868
41        -867.218523
44        -203.577653
46       -2277.001338
47       -7088.065643
48       -6291.437925
49       -2903.249052
50       -2188.673147
52        -296.850177
53       -1829.449448
55       -1906.087175
             ...
55376     -939.912831
55384    -1048.131598
55390    -2354.782702
55409    -3736.140397
55413    -6088.822599
55423    -1035.882355
55429    -2446.797144
55435     1517.377023
55440     -890.135815
55450    -3155.920480
55464    -3096.063806
55471    -1465.139250
55478     -683.605765
55482    -1362.109233
55488    -3064.643202
55496    -3726.363101
55498   -10861.039779
55504     -195.274207
55505    -2819.696988
55518    -3441.167712
55522    -2309.094414
55527     -133.106191
55539     -433.286769
55544    -3290.079319
55545     -595.836210
55547    -1036.376526
55571      -47.662166
55583    -1958.071448
55586    -2369.779287
55587    -2632.930080
Name: money2, dtype: float64

In [228]:
bank_detail_train.groupby(['ID'])['money2'].agg({'mean','sum','count'})

                sum       mean  count
ID
1       -195.332507  -2.271308     86
3      -2707.084161  -3.986869    679
4       -965.083338  -3.316438    291
9         45.288586   1.887024     24
10      -456.650397  -1.409415    324
14     -1103.818050  -0.883054   1250
16      -456.937171  -4.153974    110
21     -3113.071570  -3.764295    827
22       -95.838270  -3.422795     28
23     -2022.347780  -3.683694    549
25     -1560.388233  -2.516755    620
26      -426.445213  -9.073302     47
29     -4902.676475  -5.294467    926
31    -11080.751312  -5.941422   1865
32     -1622.899614  -4.690461    346
33     -3399.264795  -4.624850    735
35      -272.343989  -3.491590     78
36     -6292.623945  -4.231758   1487
37     -3288.245032  -5.244410    627
38     -1522.884868  -3.865190    394
41      -867.218523  -2.627935    330
44      -203.577653  -2.395031     85
46     -2277.001338  -5.808677    392
47     -7088.065643  -5.795638   1223
48     -6291.437925  -2.995923   2100
49     -2903.249052  -4.459676    651
50     -2188.673147  -2.544969    860
52      -296.850177  -3.029083     98
53     -1829.449448  -1.468258   1246
55     -1906.087175  -5.557105    343
...             ...        ...    ...
55376   -939.912831  -3.657248    257
55384  -1048.131598  -5.459019    192
55390  -2354.782702  -6.398866    368
55409  -3736.140397  -4.026013    928
55413  -6088.822599  -3.632949   1676
55423  -1035.882355  -2.690604    385
55429  -2446.797144  -4.883827    501
55435   1517.377023  10.761539    141
55440   -890.135815  -2.535999    351
55450  -3155.920480  -6.011277    525
55464  -3096.063806  -3.038335   1019
55471  -1465.139250  -3.959836    370
55478   -683.605765  -3.655646    187
55482  -1362.109233  -4.953124    275
55488  -3064.643202  -3.714719    825
55496  -3726.363101  -7.962314    468
55498 -10861.039779  -4.506656   2410
55504   -195.274207  -3.051159     64
55505  -2819.696988  -5.837882    483
55518  -3441.167712  -4.576021    752
55522  -2309.094414  -6.504491    355
55527   -133.106191  -2.047788     65
55539   -433.286769  -2.831940    153
55544  -3290.079319  -3.319959    991
55545   -595.836210  -5.729194    104
55547  -1036.376526  -5.663260    183
55571    -47.662166  -3.971847     12
55583  -1958.071448  -4.256677    460
55586  -2369.779287  -7.769768    305
55587  -2632.930080  -5.073083    519

[9294 rows x 3 columns]

In [224]:
bank_detail_train

           ID  timestamp_bank  type      money  salary  type2     money2
0        6965      5894316387     0  13.756664       0      1  13.756664
1        6965      5894321388     1  13.756664       0     -1 -13.756664
2        6965      5897553564     0  14.449810       0      1  14.449810
3        6965      5897563463     1  10.527763       0     -1 -10.527763
4        6965      5897564598     1  13.651303       0     -1 -13.651303
5        6965      5897564598     1   8.235467       0     -1  -8.235467
6        6965      5897650163     1   8.235467       0     -1  -8.235467
7        6965      5897650163     1  13.063517       0     -1 -13.063517
8        6965      5897832371     1   6.288647       0     -1  -6.288647
9        6965      5897832945     1  13.063517       0     -1 -13.063517
10       6965      5897908440     0  14.449810       0      1  14.449810
11       6965      5898040368     0  15.366101       0      1  15.366101
12       6965      5898041183     1  15.366101       0     -1 -15.366101
13       6965      5898041232     1  14.162128       0     -1 -14.162128
14       6965      5898076017     1   8.928481       0     -1  -8.928481
15       6965      5898076236     1   9.141549       0     -1  -9.141549
16       6965      5898096621     1   7.947873       0     -1  -7.947873
17       6965      5898158866     1   7.542585       0     -1  -7.542585
18       6965      5898424828     1  13.063517       0     -1 -13.063517
19       6965      5898425076     0  15.424370       0      1  15.424370
20       6965      5898425156     0  12.840374       0      1  12.840374
21       6965      5898425191     1  12.147230       0     -1 -12.147230
22       6965      5898483494     1  15.366101       0     -1 -15.366101
23       6965      5898511761     1  12.552693       0     -1 -12.552693
24       6965      5898597532     1  12.147230       0     -1 -12.147230
25       6965      5899045360     1   9.834643       0     -1  -9.834643
26       6965      5899492932     1   7.491319       0     -1  -7.491319
27       6965      5899554105     1   7.712245       0     -1  -7.712245
28       6965      5899555194     1   8.407275       0     -1  -8.407275
29       6965      5901333579     0  13.063517       0      1  13.063517
...       ...             ...   ...        ...     ...    ...        ...
6070167  8917      5914337487     1  11.454088       0     -1 -11.454088
6070168  8917      5914596687     1  13.063517       0     -1 -13.063517
6070169  8917      5914596687     1  11.454088       0     -1 -11.454088
6070170  8917      5914596687     0  11.473890       0      1  11.473890
6070171  8917      5914596687     0  13.067509       0      1  13.067509
6070172  8917      5914596687     1   7.542585       0     -1  -7.542585
6070173  8917      5914769487     0   9.844693       0      1   9.844693
6070174  8917      5914769487     0   6.849967       0      1   6.849967
6070175  8917      5914769487     1   7.542585       0     -1  -7.542585
6070176  8917      5914769487     1   9.750387       0     -1  -9.750387
6070177  8917      5914769487     0  11.464038       0      1  11.464038
6070178  8917      5914769487     1  11.454088       0     -1 -11.454088
6070179  8917      5915374287     1  12.147230       0     -1 -12.147230
6070180  8917      5915374287     0  12.147230       0      1  12.147230
6070181  8917      5917879887     0  11.454088       0      1  11.454088
6070182  8917      5917879887     1  11.454088       0     -1 -11.454088
6070183  8917      5918484687     1   6.722278       0     -1  -6.722278
6070184  8917      5918916687     0  12.147230       0      1  12.147230
6070185  8917      5918916687     1  12.147230       0     -1 -12.147230
6070186  8917      5919003087     0  11.083029       0      1  11.083029
6070187  8917      5919003087     0   7.542585       0      1   7.542585
6070188  8917      5919003087     0  10.250140       0      1  10.250140
6070189  8917      5919089487     1   7.542585       0     -1  -7.542585
6070190  8917      5919089487     1   9.621562       0     -1  -9.621562
6070191  8917      5919089487     1  11.097418       0     -1 -11.097418
6070192  8917      5919175887     1   7.542585       0     -1  -7.542585
6070193  8917      5919348687     1  10.282929       0     -1 -10.282929
6070194  8917      5919348687     1   9.151598       0     -1  -9.151598
6070195  8917      5919348687     0  10.760951       0      1  10.760951
6070196  8917      5919521487     1   9.739338       0     -1  -9.739338

[6070197 rows x 7 columns]